<?php
/**
 * This file is used to make labels which are used in configs exclusively and not in any .phtml template,
 * discoverable for PoEdit.
 * This template itself is not used for rendering + display throughout the libadmin module.
 **/

$this->translate('action_institutions_sort', 'Libadmin');
$this->translate('action_save', 'Libadmin');
$this->translate('app_title', 'Libadmin');
$this->translate('assign_institutions_to_groups_and_views', 'Libadmin');
$this->translate('bibcode', 'Libadmin');
$this->translate('canton', 'Libadmin');
$this->translate('city', 'Libadmin');
$this->translate('coordinates', 'Libadmin');
$this->translate('country', 'Libadmin');
$this->translate('country_ch', 'Libadmin');
$this->translate('country_de', 'Libadmin');
$this->translate('country_fr', 'Libadmin');
$this->translate('country_it', 'Libadmin');
$this->translate('country_li', 'Libadmin');
$this->translate('display_links_for_control', 'Libadmin');
$this->translate('email', 'Libadmin');
$this->translate('facebook', 'Libadmin');
$this->translate('internal_notes', 'Libadmin');
$this->translate('is_active', 'Libadmin');
$this->translate('isil', 'Libadmin');
$this->translate('language_english', 'Libadmin');
$this->translate('language_french', 'Libadmin');
$this->translate('language_german', 'Libadmin');
$this->translate('language_italian', 'Libadmin');
$this->translate('navigation_admin', 'Libadmin');
$this->translate('navigation_groups', 'Libadmin');
$this->translate('navigation_home', 'Libadmin');
$this->translate('navigation_institutions', 'Libadmin');
$this->translate('navigation_views', 'Libadmin');
$this->translate('no', 'Libadmin');
$this->translate('pagedescription_administration', 'Libadmin');
$this->translate('skype', 'Libadmin');
$this->translate('syscode', 'Libadmin');
$this->translate('telefon', 'Libadmin');
$this->translate('webseite', 'Libadmin');
$this->translate('zip', 'Libadmin');

$this->translate('group_add', 'Libadmin');
$this->translate('notfound_record', 'Libadmin');
$this->translate('group_edit', 'Libadmin');
$this->translate('saved_institution', 'Libadmin');
$this->translate('institution_add', 'Libadmin');
$this->translate('institution_edit', 'Libadmin');
$this->translate('view_add', 'Libadmin');
$this->translate('view_edit', 'Libadmin');
$this->translate('twitter', 'Libadmin');
$this->translate('attention_relations', 'Libadmin');
$this->translate('sortInstitutions', 'Libadmin');
$this->translate('no_institutions', 'Libadmin');
$this->translate('maketopmostitem', 'Libadmin');
$this->translate('makebottommostitem', 'Libadmin');
$this->translate('action_groups_sort_for_view', 'Libadmin');
$this->translate('views ', 'Libadmin');
$this->translate('edit_view', 'Libadmin');
$this->translate('navigation_view', 'Libadmin');
