<?php
/**
 * This file is used to make labels which are used in configs exclusively and not in any .phtml template,
 * discoverable for PoEdit.
 * This template itself is not used for rendering + display throughout the libadmin module.
 **/

$this->translate('action_institutions_sort');
$this->translate('action_save');
$this->translate('app_title');
$this->translate('assign_institutions_to_groups_and_views');
$this->translate('bibcode');
$this->translate('canton');
$this->translate('city');
$this->translate('coordinates');
$this->translate('country');
$this->translate('country_ch');
$this->translate('country_de');
$this->translate('country_fr');
$this->translate('country_it');
$this->translate('country_li');
$this->translate('display_links_for_control');
$this->translate('email');
$this->translate('facebook');
$this->translate('internal_notes');
$this->translate('is_active');
$this->translate('isil');
$this->translate('language_english');
$this->translate('language_french');
$this->translate('language_german');
$this->translate('language_italian');
$this->translate('navigation_admin');
$this->translate('navigation_groups');
$this->translate('navigation_home');
$this->translate('navigation_institutions');
$this->translate('navigation_views');
$this->translate('no');
$this->translate('pagedescription_administration');
$this->translate('skype');
$this->translate('syscode');
$this->translate('telefon');
$this->translate('webseite');
$this->translate('zip');

$this->translate('group_add');
$this->translate('notfound_record');
$this->translate('group_edit');
$this->translate('saved_institution');
$this->translate('institution_add');
$this->translate('institution_edit');
$this->translate('view_add');
$this->translate('view_edit');
$this->translate('twitter');
$this->translate('attention_relations');
$this->translate('sortInstitutions');
$this->translate('no_institutions');
$this->translate('maketopmostitem');
$this->translate('makebottommostitem');
$this->translate('action_groups_sort_for_view');
$this->translate('views');
$this->translate('edit_view');
$this->translate('navigation_view');

$this->translate('app_title');