<?php
	/**
	 * This file is used to make labels which are used in configs exclusively and not in any .phtml template,
	 * discoverable for PoEdit.
	 * This template itself is not used for rendering + display throughout the libadmin module.
	**/
?>
<?= $this->translate('app_title',				'Libadmin') ?>'
<?= $this->translate('navigation_home',			'Libadmin') ?>'
<?= $this->translate('navigation_institutions',	'Libadmin') ?>'
<?= $this->translate('navigation_groups',		'Libadmin') ?>'
<?= $this->translate('navigation_views',		'Libadmin') ?>'
<?= $this->translate('navigation_admin',		'Libadmin') ?>'
