<div class="topButtons">
	<a href="<?= $this->url($route, array('action' => 'add')); ?>"
	   class="ajaxButton addButton btn btn-primary btn-medium" id="add-<?= strtolower($entityName) ?>">
		<?= $this->translate('add_new_xxx', 'Libadmin') ?> <?= $entityName ?>
	</a>
</div>
<h1><?= $entityNamePlural ?></h1>

<?php if (is_null($listItems) || $listItems->count() == 0): ?>
	<?php
	$baseLabel = $this->translate('home_no_records', 'Libadmin');
	echo sprintf($baseLabel, $entityNamePlural);
	?>
<?php else: ?>
	<p><?= $this->translate('home_select_record', 'Libadmin') ?></p>
<?php endif ?>