<div class="topButtons">
	<a href="<?=$this->url(strtolower($entityName), array('action'=>'add'));?>" class="ajaxButton addButton btn btn-primary btn-medium" id="add-<?=strtolower($entityName)?>">
		Add new <?=$entityName?>
	</a>
</div>
<h1>Manage <?=$entityNamePlural?></h1>

<?php if( is_null($listItems) || $listItems->count() == 0 ): ?>
	<p>There are no <?=strtolower($entityNamePlural)?> stored yet.</p>
<?php else: ?>
	<p>Please select a <?=strtolower($entityName)?> on the left</p>
<?php endif ?>