Home view

<?php return; ?>


<table class="table">
    <tr>
        <th>library ID</th>
        <th>Struktur</th>
    </tr>



    <?php foreach ($libraries as $library) : ?>
    <tr>
        <?php
        $elements = $library->getLibraryElements();
                ?>

        <td><?php echo $this->escapeHtml($library->libraryid);?></td>
        <td>
            <table class="table">
                <tr>
                    <th>ElementName</th>
                    <th>Wert</th>
                </tr>
                <tr>
                <table>


                    <?php foreach ($elements as $name => $val) : ?>
                        <?php if ($name != "adress" && $name != "translations") :?>
                        <tr>
                          <td>
                            <?php echo $this->escapeHtml($name);?>
                          </td>

                          <td>
                              <?php echo $this->escapeHtml($val);?>
                          </td>
                        </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </table>
                </tr>
            </table>

    </tr>


    <?php endforeach; ?>

</table>