<?php

$this->headTitle($title);

$form = $this->form;
$form->prepare();

$idGroup		= (int)$form->get('id')->getValue();
$isNew			= !$idGroup;

$LabelNew		= $this->translate('buttonlabelcreate',	'Libadmin');
$LabelUpdate	= $this->translate('buttonlabelupdate',	'Libadmin');
$saveButtonLabel= $isNew ? $LabelNew : $labelUpdate;

$formType	= 'horizontal';
$group		= $form->get('group');

?>


<?=$this->formTwb()->openTag($form, $formType)?>

	<div class="topButtons">
		<input type="submit" value="<?=$this->escapeHtml($saveButtonLabel)?>" class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
		<a href="<?=$this->url('group', array('action'=>'home'));?>" class="ajaxButton closeButton btn btn-medium" id="closebutton">Close</a>
		<?php if(!$isNew): ?>
			<a href="<?=$this->url('group', array('action'=>'delete', 'id' => $idGroup));?>" class="ajaxButton deleteButton btn btn-danger btn-medium" id="deletebutton">Delete</a>
		<?php endif; ?>
	</div>

	<h1><?php echo $this->escapeHtml($title); ?></h1>

	<?=$this->ztbFlashMessenger()->render()?>

	<fieldset class="general">
		<legend>Allgemein</legend>
		<div class="row-fluid">
			<div class="span10">
				<?=$this->formRowTwb($form->get('code'))?>
			</div>
			<div class="span2">
				<?=$this->formRowTwb($form->get('is_active'))?>
			</div>
		</div>
	</fieldset>

	<div class="tabbable">
		<ul class="nav nav-tabs formTabs">
			<li class="active">
				<a href="#display">Anzeige</a>
			</li>
			<li><a href="#views">Views</a></li>
			<li><a href="#institutions">Institutionen</a></li>
		</ul>

		<div class="tab-content">

				<div class="tab-pane active" id="display">

					<fieldset>
						<legend>Display Namen</legend>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_de'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_fr'))?>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_it'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_en'))?>
							</div>
						</div>
					</fieldset>

					<fieldset class="notes">
						<legend>Notizen</legend>
						<?=$this->formRowTwb($form->get('notes'))?>
					</fieldset>

				</div>

				<div class="tab-pane" id="views">
					<?=$this->formRowTwb($form->get('views'))?>
				</div>

				<div class="tab-pane" id="institutions">
					<p>Institutions</p>
				</div>

		</div>

	</div>

<?=$this->form()->closeTag();?>