<?php
$this->headTitle($title);

$form = $this->form;
$form->prepare();

$idGroup		= (int)$form->get('id')->getValue();
$isNew			= !$idGroup;

$saveButtonLabel= $this->translate($isNew ? 'action_create' : 'action_update',	'Libadmin');

$formType	= 'horizontal';
$group		= $form->get('group');

	// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>

<?=$this->formTwb()->openTag($form, $formType)?>
	<div class="topButtons">
		<input type="submit" value="<?=$this->escapeHtml($saveButtonLabel)?>" class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
		<a href="<?=$this->url('group', array('action'=>'home'));?>" class="ajaxButton closeButton btn btn-medium" id="closebutton"><?= $this->translate('action_close', 'Libadmin') ?></a>
		<?php if(!$isNew): ?>
			<a href="<?=$this->url('group', array('action'=>'delete', 'id' => $idGroup));?>" class="ajaxButton deleteButton btn btn-danger btn-medium" id="deletebutton">
				<?= $this->translate('action_delete', 'Libadmin') ?>
			</a>
		<?php endif; ?>
	</div>

	<h1><?php echo $this->escapeHtml($title); ?></h1>

	<?=$this->ztbFlashMessenger()->render()?>

	<fieldset class="general">
		<legend><?= $this->translate('general', 'Libadmin') ?></legend>
		<div class="row-fluid">
			<div class="span10">
				<?=$this->formRowTwb($form->get('code'))?>
			</div>
			<div class="span2">
				<?=$this->formRowTwb($form->get('is_active'))?>
			</div>
		</div>
	</fieldset>

	<div class="tabbable">
		<ul class="nav nav-tabs formTabs">
			<li class="active">
				<a href="#display"><?= $this->translate('display', 'Libadmin') ?></a>
			</li>
			<li><a href="#views"><?= $this->translate('views ', 'Libadmin') ?></a></li>
			<li><a href="#institutions"><?= $this->translate('institutions', 'Libadmin') ?></a></li>
		</ul>

		<div class="tab-content">
				<div class="tab-pane active" id="display">
					<fieldset>
						<legend><?= $this->translate('displaynames', 'Libadmin') ?></legend>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_de'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_fr'))?>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_it'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_en'))?>
							</div>
						</div>
					</fieldset>

					<fieldset class="notes">
						<legend><?= $this->translate('notes', 'Libadmin') ?></legend>
						<?=$this->formRowTwb($form->get('notes'))?>
					</fieldset>
				</div>

				<div class="tab-pane" id="views">
					<?=$this->formRowTwb($form->get('views'))?>
				</div>

				<div class="tab-pane" id="institutions">
					<p><?= $this->translate('institutions', 'Libadmin') ?></p>
				</div>
		</div>
	</div>

<?=$this->form()->closeTag();?>