<?php

$this->headTitle($title);

$form = $this->form;
$form->prepare();

$saveButtonLabel	= $form->get('id')->getValue() ? 'Update' : 'Add';

?>

<?=$this->form()->openTag($form)?>

	<div class="topButtons">
		<input type="submit" value="<?=$this->escapeHtml($saveButtonLabel)?>" class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
		<input type="button" value="Close" class="closeButton btn btn-medium" id="closebutton" name="close">
		<input type="button" value="Delete" class="closeButton btn btn-danger btn-medium" id="deletebutton" name="delete">
	</div>

	<h1><?php echo $this->escapeHtml($title); ?></h1>

	<p>On top of the tabs</p>

	<p>ID: <?=$form->get('id')->getValue()?></p>

	<div class="tabbable">
		<ul class="nav nav-tabs formTabs">
			<li class="active">
				<a href="#display">Anzeige</a>
			</li>
			<li><a href="#address">Adresse</a></li>
			<li><a href="#linking">Gruppen &amp; Views</a></li>
		</ul>

		<div class="tab-content">

				<div class="tab-pane active" id="display">

					<fieldset>
						<legend>Test</legend>
						<?php
							echo $this->formHidden($form->get('id'));
							echo $this->formRow($form->get('bib_code'));
							echo $this->formRow($form->get('label_de'));
						?>
					</fieldset>

					<fieldset>
						<legend>Test 2</legend>
						<p>sdfasdf sadf asdfa sdfa sdf</p>
					</fieldset>

				</div>

				<div class="tab-pane" id="address">
					Address
				</div>

				<div class="tab-pane" id="linking">
					linking
				</div>

		</div>

	</div>

<?=$this->form()->closeTag();?>