<?php

$this->headTitle($title);

$form = $this->form;
$form->prepare();

$isNew			= $form->get('id')->getValue() === null;
$saveButtonLabel= $isNew ? 'Create' : 'Update';
$formType		= 'horizontal';

//if( isset($messages) ) {
//	var_dump($messages);
//}

?>


<?=$this->formTwb()->openTag($form, $formType)?>

	<div class="topButtons">
		<input type="submit" value="<?=$this->escapeHtml($saveButtonLabel)?>" class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
		<a href="<?=$this->url('institution', array('action'=>'home'));?>" class="ajaxButton closeButton btn btn-medium" id="closebutton">Close</a>
		<?php if(!$isNew): ?>
			<a href="<?=$this->url('institution', array('action'=>'delete'));?>" class="ajaxButton deleteButton btn btn-danger btn-medium" id="deletebutton">Delete</a>
		<?php endif; ?>
	</div>

	<h1><?php echo $this->escapeHtml($title); ?></h1>

	<p>ID: <?=$form->get('id')->getValue()?></p>

	<?=$this->ztbFlashMessenger()->render()?>

	<fieldset class="institutionGeneral">
		<legend>Allgemein</legend>
		<div class="row-fluid">
			<div class="span5">
				<?=$this->formRowTwb($form->get('bib_code'))?>
			</div>
			<div class="span5">
				<?=$this->formRowTwb($form->get('sys_code'))?>
			</div>
			<div class="span2">
				<?=$this->formRowTwb($form->get('is_active'))?>
			</div>
		</div>
	</fieldset>

	<div class="tabbable">
		<ul class="nav nav-tabs formTabs">
			<li class="active">
				<a href="#display">Anzeige</a>
			</li>
			<li><a href="#address">Adresse</a></li>
			<li><a href="#linking">Gruppen &amp; Views</a></li>
		</ul>

		<div class="tab-content">

				<div class="tab-pane active" id="display">

					<fieldset>
						<legend>Display Namen</legend>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_de'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_fr'))?>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_it'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('label_en'))?>
							</div>
						</div>
					</fieldset>

					<fieldset>
						<legend>Bibliotheksnamen (offiziell)</legend>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('name_de'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('name_fr'))?>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('name_it'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('name_en'))?>
							</div>
						</div>
					</fieldset>

					<fieldset>
						<legend>URL Bibliotheksinformationen</legend>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('url_de'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('url_fr'))?>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span6">
								<?=$this->formRowTwb($form->get('url_it'))?>
							</div>
							<div class="span6">
								<?=$this->formRowTwb($form->get('url_en'))?>
							</div>
						</div>
					</fieldset>

				</div>

				<div class="tab-pane" id="address">
					Address
				</div>

				<div class="tab-pane" id="linking">
					linking
				</div>

		</div>

	</div>

<?=$this->form()->closeTag();?>