
<form id="search-form" class="searchForm form-search" action="<?=$this->url('institution', array('action'=>'search'));?>">
	<input id="search-query" name="query" type="text" class="search-query" placeholder="Search">
</form>
<ul id="search-results-list" class="searchResultList nav nav-tabs nav-stacked">
	<?=$this->render('libadmin/global/search', array(
		'listItems'	=> $searchResults,
		'route'		=> 'institution'
	));?>
</ul>

