<?php
$this->headTitle($title);

$form = $this->form;
$form->prepare();

$idView = (int)$form->get('id')->getValue();
$isNew = !$idView;

$saveButtonLabel = $this->translate($isNew ? 'action_create' : 'action_save', 'Libadmin');

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');

?>

<?= $this->formTwb()->openTag($form, $formType) ?>
	<!-- ------------------- CRUD buttons: create/save, close, delete  -->
	<div class="topButtons">
		<input type="submit" value="<?= $this->escapeHtml($saveButtonLabel) ?>"
			   class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
		<a href="<?= $this->url('view', array('action' => 'home')); ?>" class="ajaxButton closeButton btn btn-medium"
		   id="closebutton">
			<?= $this->translate('action_close', 'Libadmin') ?>
		</a>
		<?php if (!$isNew): ?>
			<a href="<?= $this->url('view', array('action' => 'delete', 'id' => $idView)); ?>"
			   class="ajaxButton deleteButton btn btn-danger btn-medium" id="deletebutton">
				<?= $this->translate('action_delete', 'Libadmin') ?>
			</a>
		<?php endif; ?>
	</div>

	<h1><?php echo $this->escapeHtml($title); ?></h1>

<?= $this->ztbFlashMessenger()->render() ?>

	<!-- ------------------- General data fieldset: code, label, is active -->
	<fieldset class="general">
		<legend><?= $this->translate('general', 'Libadmin') ?></legend>
		<div class="row-fluid">
			<div class="span5"><?= $this->formRowTwb($form->get('code')) ?></div>
			<div class="span5"><?= $this->formRowTwb($form->get('label')) ?></div>
			<div class="span2"><?= $this->formRowTwb($form->get('is_active')) ?></div>
		</div>
	</fieldset>

	<div class="tabbable">
		<!-- ------------------- View Area tabs menu -->
		<ul class="nav nav-tabs formTabs">
			<li class="active"><a href="#display"><?= $this->translate('display', 'Libadmin') ?></a></li>
			<li><a href="#groups"><?= $this->translate('action_groups_activate', 'Libadmin') ?></a></li>
			<li><a href="#groupsort"><?= $this->translate('action_groups_sort', 'Libadmin') ?></a></li>
			<li><a href="#institutionsort"><?= $this->translate('action_institutions_sort', 'Libadmin') ?></a></li>
			<li><a href="#relations"><?= $this->translate('linking', 'Libadmin') ?></a></li>
		</ul>

		<!-- ------------------- Tabs content container -->
		<div class="tab-content">

			<!-- ------------------- Tab Pane: Display (internal notes) -->
			<div class="tab-pane active" id="display">
				<fieldset class="notes">
					<legend><?= $this->translate('notes', 'Libadmin') ?></legend>
					<?= $this->formRowTwb($form->get('notes')) ?>
				</fieldset>
			</div>

			<!-- ------------------- Tab Pane: Activate Groups -->
			<div class="tab-pane" id="groups">
				<?php if($form->get('groups')): ?>
					<p><?= $this->translate('header_active_networkgroups', 'Libadmin') ?></p>
					<?= $this->formRowTwb($form->get('groups')) ?>
				<?php else: ?>
					<p><?= $this->translate('nogroups', 'Libadmin') ?></p>
				<?php endif; ?>
			</div>

			<!-- ------------------- Tab Pane: Sort Groups -->
			<div class="tab-pane" id="groupsort">
				<div class="row">
					<div class="span8">
						<ul id="groupssortable" class="nav nav-tabs nav-stacked">
							<?php /** @var	Libadmin\Model\Group[] 	$groups */ ?>
							<?php foreach($groups as $group): ?>
								<li class="ui-state-default">
									<a href="#"><?= $group->getListLabel() ?></a>
								</li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
			</div>

			<!-- ------------------- Tab Pane: Sort Institutions -->
			<div class="tab-pane" id="institutionsort">
				<div class="row">
					<div class="span8">
						<ul id="institutionssortable" class="nav nav-tabs nav-stacked">
							<?php /** @var	Libadmin\Model\Institution[] 	$institutions */ ?>
							<?php foreach($institutions as $institution): ?>
								<li class="ui-state-default">
									<a href="#"><?= $institution->getListLabel() ?></a>
								</li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
			</div>

			<!-- ------------------- Tab Pane: View Relations -->
			<div class="tab-pane" id="relations">
				<?php if (isset($relations) && sizeof($relations) > 0): ?>

					<?php foreach ($relations as $groupRelation): ?>
						<h4><?= $this->escapeHtml($groupRelation['group']->getListLabel()) ?></h4>

						<table class="table table-striped table-condensed">
							<thead>
							<tr>
								<th class="nr">#</th>
								<th class="institution"><?= $this->translate('institution', 'Libadmin') ?></th>
								<th class="codes"><?= $this->translate('bibsyscodes', 'Libadmin') ?></th>
								<th class="favorite"><?= $this->translate('is_favorite', 'Libadmin') ?></th>
							</tr>
							</thead>
							<tbody>
							<?php
							$counter = 1;
							/** @var \Libadmin\Model\Institution $institution */
							?>
							<?php foreach ($groupRelation['institutions'] as $institution): ?>
								<tr>
									<td><?= $counter++ ?></td>
									<td><?= $this->escapeHtml($institution->getListLabel()) ?></td>
									<td><?= $this->escapeHtml($institution->getBib_code()) ?>
										/ <?= $this->escapeHtml($institution->getSys_code()) ?></td>
									<td><?= $this->translate($institution->isFavorite() ? 'yes' : 'no', 'Libadmin') ?></td>
								</tr>
							<?php endforeach; ?>
							</tbody>
						</table>

					<?php endforeach; ?>
				<?php else: ?>
					<p><?= $this->translate('no_relations', 'Libadmin') ?></p>
				<?php endif; ?>

			</div>
		</div>
	</div>

<?= $this->form()->closeTag(); ?>