<?php
$this->headTitle($this->translate($title));

$form = $this->customform;
$form->prepare();

$admininstitution = $form->get('admininstitution');
$formType = 'horizontal';
$form->setAttribute('class', 'form-horizontal');
$saveButtonLabel = $this->translate($isNew ? 'action_create' : 'action_save');


?>


<?= $this->form()->openTag($form) ?>
<div class="topButtons">
    <input type="submit" value="<?= $this->escapeHtml($saveButtonLabel) ?>"
           class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
    <a href="<?= $this->url('institution', ['action' => 'home']); ?>"
       class="ajaxButton closeButton btn btn-medium" id="closebutton">
        <?= $this->translate('action_close') ?>
    </a>
    <?php if (!$isNew): ?>
        <a href="<?= $this->url('institution', ['action' => 'delete', 'id' => $admininstitution->get('id')->getValue()]); ?>"
           class="ajaxButton deleteButton btn btn-danger btn-medium" id="deletebutton">
            <?= $this->translate('action_delete') ?>
        </a>
    <?php endif; ?>
</div>

<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>

<?= $this->flashMessenger()->render('success', array('alert', 'alert-success')) ?>
<?= $this->flashMessenger()->render('error', array('alert', 'alert-error')) ?>

<fieldset class="general">
    <legend><?= $this->translate('general') ?></legend>
    <div class="row-fluid">
        <div class="span5"><?= $this->formRow($admininstitution->get('idcode')) ?></div>
    </div>
</fieldset>


<div class="tabbable">
    <ul class="nav nav-tabs formTabs">
        <li class="active"><a href="#address"><?= $this->translate('address') ?></a></li>
        <li><a href="#admin"><?= $this->translate('admin') ?></a></li>
        <li><a href="#costs"><?= $this->translate('costs_participation') ?></a></li>

    </ul>


    <div class="tab-content">
        <div class="tab-pane active" id="address">
            <fieldset>
                <legend><?= $this->translate('displaynames') ?></legend>
                <div class="row-fluid">
                    <div class="span12"><?= $this->formRow($admininstitution->get('name')) ?></div>
                </div>
            </fieldset>

            <div class="row-fluid">
                <div class="span12"><?= $this->formRow($admininstitution->get('email')) ?></div>
            </div>

            <div class="row-fluid">
                <div class="span12"><?= $this->formRow($admininstitution->get('korrespondezsprache')) ?></div>
            </div>

            <fieldset class="postAdresse">
                <legend><?= $this->translate('postAdresse') ?></legend>
                <div class="row-fluid">
                    <div class="span6">
                        <?php $postAdresseFieldset = $admininstitution->get('postadresse') ?>
                        <?= $this->formRow($postAdresseFieldset->get('strasse')) ?>
                        <?= $this->formRow($postAdresseFieldset->get('nummer')) ?>
                        <?= $this->formRow($postAdresseFieldset->get('zusatz')) ?>
                        <?= $this->formRow($postAdresseFieldset->get('plz')) ?>
                        <?= $this->formRow($postAdresseFieldset->get('ort')) ?>
                        <?= $this->formRow($postAdresseFieldset->get('country')) ?>
                        <?= $this->formRow($postAdresseFieldset->get('canton')) ?>
                    </div>
                </div>
            </fieldset>

            <fieldset class="contactPerson">
                <legend><?= $this->translate('contactPerson') ?></legend>
                <div class="row-fluid">
                    <div class="span6">
                        <?php $kontaktFieldset = $admininstitution->get('kontakt') ?>
                        <?= $this->formRow($kontaktFieldset->get('name')) ?>
                        <?= $this->formRow($kontaktFieldset->get('vorname')) ?>
                        <?= $this->formRow($kontaktFieldset->get('anrede')) ?>
                        <?= $this->formRow($kontaktFieldset->get('email')) ?>
                    </div>
                </div>
            </fieldset>


        </div>


        <div class="tab-pane" id="admin">
            <fieldset>
                <legend><?= $this->translate('admin') ?></legend>



                <div class="row-fluid">
                    <div class="span12"><?= $this->formRow($admininstitution->get('bfscode')) ?></div>
                </div>
                <div class="row-fluid">
                    <div class="span12"><?= $this->formRow($admininstitution->get('ipadresse')) ?></div>
                </div>
                <div class="row-fluid">
                    <div class="span12"><?= $this->formRow($admininstitution->get('zusage_beitrag')) ?></div>
                </div>


            </fieldset>

        </div>


        <div class="tab-pane" id="costs">
            <div class="tab-pane" id="costs">
                <fieldset>
                    <legend>Kostenbeitrag</legend>

                    <div class="row-fluid">
                        <div class="span12"><?= $this->formRow($admininstitution->get('kostenbeitrag_basiert_auf')) ?></div>
                    </div>

                    <div class="span6">
                        <?php $kostenbeitragFieldset = $admininstitution->get('kostenbeitrag') ?>
                        <?= $this->formRow($kostenbeitragFieldset->get('j2018')) ?>
                        <?= $this->formRow($kostenbeitragFieldset->get('j2019')) ?>
                        <?= $this->formRow($kostenbeitragFieldset->get('j2020')) ?>
                    </div>

                    <div class="row-fluid">
                        <div class="span12"><?= $this->formRow($admininstitution->get('bemerkung_kostenbeitrag')) ?></div>
                    </div>


                </fieldset>

                <fieldset>
                    <legend>Rechnung</legend>

                    <div class="row-fluid">
                        <div class="span12"><?= $this->formRow($admininstitution->get('adresse_rechnung_gleich_post')) ?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formRow($admininstitution->get('mwst')) ?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formRow($admininstitution->get('grund_mwst_frei')) ?></div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12"><?= $this->formRow($admininstitution->get('e_rechnung')) ?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formRow($admininstitution->get('bemerkung_rechnung')) ?></div>
                    </div>
                </fieldset>

                <fieldset class="rechnungsAdresse">
                    <legend><?= $this->translate('rechnungsAdresse') ?></legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php $rechnungsAdresseFieldset = $admininstitution->get('rechnungsadresse') ?>
                            <?= $this->formRow($rechnungsAdresseFieldset->get('name_organisation_rechnung')) ?>
                            <?= $this->formRow($rechnungsAdresseFieldset->get('strasse')) ?>
                            <?= $this->formRow($rechnungsAdresseFieldset->get('nummer')) ?>
                            <?= $this->formRow($rechnungsAdresseFieldset->get('zusatz')) ?>
                            <?= $this->formRow($rechnungsAdresseFieldset->get('plz')) ?>
                            <?= $this->formRow($rechnungsAdresseFieldset->get('ort')) ?>
                            <?= $this->formRow($rechnungsAdresseFieldset->get('country')) ?>
                            <?= $this->formRow($rechnungsAdresseFieldset->get('canton')) ?>

                        </div>
                    </div>
                </fieldset>

                <fieldset class="contactRechnung">
                    <legend><?= $this->translate('contactPersonInvoice') ?></legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php $kontaktRechnungFieldset = $admininstitution->get('kontakt_rechnung') ?>
                            <?= $this->formRow($kontaktRechnungFieldset->get('name')) ?>
                            <?= $this->formRow($kontaktRechnungFieldset->get('vorname')) ?>
                            <?= $this->formRow($kontaktRechnungFieldset->get('anrede')) ?>
                            <?= $this->formRow($kontaktRechnungFieldset->get('email')) ?>
                        </div>
                    </div>
                </fieldset>

        </div>



    </div>


<?= $this->form()->closeTag(); ?>