<?php
$this->headTitle($this->translate($title));

$form = $this->customform;
$form->prepare();

$admininstitution = $form->get('admininstitution');
$formType = 'horizontal';
$form->setAttribute('class', 'form-horizontal');
$saveButtonLabel = $this->translate($isNew ? 'action_create' : 'action_save');


?>


<?= $this->form()->openTag($form) ?>
<div class="topButtons">
    <input type="submit" value="<?= $this->escapeHtml($saveButtonLabel) ?>"
           class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
    <a href="<?= $this->url('institution', ['action' => 'home']); ?>"
       class="ajaxButton closeButton btn btn-medium" id="closebutton">
        <?= $this->translate('action_close') ?>
    </a>
    <?php if (!$isNew): ?>
        <a href="<?= $this->url('institution', ['action' => 'delete', 'id' => $admininstitution->get('id')->getValue()]); ?>"
           class="ajaxButton deleteButton btn btn-danger btn-medium" id="deletebutton">
            <?= $this->translate('action_delete') ?>
        </a>
    <?php endif; ?>
</div>

<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>

<?= $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success')) ?>
<?= $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-error')) ?>

<?= $this->flashMessenger()->render('success', array('alert', 'alert-success')) ?>
<?= $this->flashMessenger()->render('error', array('alert', 'alert-error')) ?>

<fieldset class="general">
    <legend><?= $this->translate('general') ?></legend>
    <div class="row-fluid">
        <div class="span5"><?= $this->formBootstrapRow($admininstitution,'idcode') ?></div>
        <div class="span5"><?= $this->formBootstrapRow($admininstitution,'name') ?></div>
    </div>
</fieldset>


<div class="tabbable">
    <ul class="nav nav-tabs formTabs">
        <li class="active"><a href="#address"><?= $this->translate('address') ?></a></li>
        <li><a href="#admin"><?= $this->translate('admin') ?></a></li>
        <li><a href="#costs"><?= $this->translate('costs_participation') ?></a></li>

    </ul>


    <div class="tab-content">
        <div class="tab-pane active" id="address">
            <fieldset>
                <div class="row-fluid">
                    <div class="span12"><?= $this->formBootstrapRow($admininstitution,'email') ?></div>
                </div>
                <div class="row-fluid">
                    <div class="span12"><?= $this->formBootstrapRow($admininstitution,'korrespondenzsprache') ?></div>
                </div>
            </fieldset>



            <fieldset class="postAdresse">
                <legend><?= $this->translate('postAdresse') ?></legend>
                <div class="row-fluid">
                    <div class="span6">
                        <?php $postAdresseFieldset = $admininstitution->get('postadresse') ?>
                        <?= $this->formBootstrapRow($postAdresseFieldset,'name_organisation') ?>
                        <?= $this->formBootstrapRow($postAdresseFieldset,'strasse') ?>
                        <?= $this->formBootstrapRow($postAdresseFieldset,'nummer') ?>
                        <?= $this->formBootstrapRow($postAdresseFieldset,'zusatz') ?>
                        <?= $this->formBootstrapRow($postAdresseFieldset,'plz') ?>
                        <?= $this->formBootstrapRow($postAdresseFieldset,'ort') ?>
                        <?= $this->formBootstrapRow($postAdresseFieldset,'country') ?>
                        <?= $this->formBootstrapRow($postAdresseFieldset,'canton') ?>
                    </div>
                </div>
            </fieldset>

            <fieldset class="contactPerson">
                <legend><?= $this->translate('contactPerson') ?></legend>
                <div class="row-fluid">
                    <div class="span6">
                        <?php $kontaktFieldset = $admininstitution->get('kontakt') ?>
                        <?= $this->formBootstrapRow($kontaktFieldset,'anrede') ?>
                        <?= $this->formBootstrapRow($kontaktFieldset,'vorname') ?>
                        <?= $this->formBootstrapRow($kontaktFieldset,'name') ?>
                        <?= $this->formBootstrapRow($kontaktFieldset,'email') ?>
                    </div>
                </div>
            </fieldset>


        </div>


        <div class="tab-pane" id="admin">
            <fieldset>
                <legend><?= $this->translate('admin') ?></legend>



                <div class="row-fluid">
                    <div class="span12"><?= $this->formBootstrapRow($admininstitution,'bfscode') ?></div>
                </div>
                <div class="row-fluid">
                    <div class="span12"><?= $this->formBootstrapRow($admininstitution,'ipadresse') ?></div>
                </div>


            </fieldset>

        </div>


        <div class="tab-pane" id="costs">
            <div class="tab-pane" id="costs">
                <fieldset>
                    <legend>Kostenbeitrag</legend>

                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($admininstitution,'kostenbeitrag_basiert_auf') ?></div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($admininstitution, 'zusage_beitrag') ?></div>
                    </div>

                    <?php $kostenbeitragFieldset = $admininstitution->get('kostenbeitrag') ?>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($kostenbeitragFieldset,'j2018') ?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($kostenbeitragFieldset,'j2019') ?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($kostenbeitragFieldset,'j2020') ?></div>
                    </div>

                    <div class="row-fluid">
                        <?= $this->formBootstrapRow($admininstitution,'bemerkung_kostenbeitrag') ?>
                    </div>


                </fieldset>

                <fieldset>
                    <legend>Rechnung</legend>

                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($admininstitution,'adresse_rechnung_gleich_post') ?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($admininstitution,'mwst') ?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($admininstitution,'grund_mwst_frei') ?></div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($admininstitution,'e_rechnung') ?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12"><?= $this->formBootstrapRow($admininstitution,'bemerkung_rechnung') ?></div>
                    </div>
                </fieldset>

                <fieldset class="rechnungsAdresse">
                    <legend><?= $this->translate('rechnungsAdresse') ?></legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php $rechnungsAdresseFieldset = $admininstitution->get('rechnungsadresse') ?>
                            <?= $this->formBootstrapRow($rechnungsAdresseFieldset,'name_organisation') ?>
                            <?= $this->formBootstrapRow($rechnungsAdresseFieldset,'strasse') ?>
                            <?= $this->formBootstrapRow($rechnungsAdresseFieldset,'nummer') ?>
                            <?= $this->formBootstrapRow($rechnungsAdresseFieldset,'zusatz') ?>
                            <?= $this->formBootstrapRow($rechnungsAdresseFieldset,'plz') ?>
                            <?= $this->formBootstrapRow($rechnungsAdresseFieldset,'ort') ?>
                            <?= $this->formBootstrapRow($rechnungsAdresseFieldset,'country') ?>
                            <?= $this->formBootstrapRow($rechnungsAdresseFieldset,'canton') ?>

                        </div>
                    </div>
                </fieldset>

                <fieldset class="contactRechnung">
                    <legend><?= $this->translate('contactPersonInvoice') ?></legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php $kontaktRechnungFieldset = $admininstitution->get('kontakt_rechnung') ?>
                            <?= $this->formBootstrapRow($kontaktRechnungFieldset,'anrede') ?>
                            <?= $this->formBootstrapRow($kontaktRechnungFieldset,'vorname') ?>
                            <?= $this->formBootstrapRow($kontaktRechnungFieldset,'name') ?>
                            <?= $this->formBootstrapRow($kontaktRechnungFieldset,'email') ?>
                        </div>
                    </div>
                </fieldset>

        </div>



    </div>


<?= $this->form()->closeTag(); ?>