<?php
namespace Libadmin\Form\Element;

use Libadmin\Model\InstitutionRelation;

/**
 * [Description]
 *
 */
class InstitutionList extends MultiSelect
{

	public function __construct($name = null, $options = array())
	{
		parent::__construct($name, $options);

		$this->disableInArrayValidator = true;

		$this->setAttribute('size', 20);
	}



	public function setValue($value)
	{
		$options = array();

		if (is_array($value) && sizeof($value)) {
			if ($value[0] instanceof InstitutionRelation) {
				/** @var InstitutionRelation $institutionRelation */
				foreach ($value as $institutionRelation) {
					$options[] = $institutionRelation->getIdInstitution();
				}
			} else {
				$options = $value;
			}
		}


//
//		if (is_array($value)) {
//			/** @var InstitutionRelation $institutionRelation */
//			foreach ($value as $institutionRelation) {
//				$options[] = $institutionRelation->getIdInstitution();
//			}
//		}

		return parent::setValue($options); // TODO: Change the autogenerated stub
	}

}
